export const optionalNodes = [
  "overview",
  "people",
  "places",
  "events",
  "history",
  "related",
  "effects",
  "beliefs",
  "superstitions",
  "cause of",
  "inventions",
  "influences",
  // "examples",
  // "types",
  "foundations",
  "principles",
  "laws",
  "theories",
  "applications",
  "processes",
  "contradictions",
  "problems",
  "solutions",
  "benefits",
  "risks",
  "quotes",
  "statistics",
  "facts",
  "myths",
  "misconceptions",
  "questions",
  "answers",
  "famous works",

  // "requirements",
  // "discoveries",
]
